### ISSUE TITLE
Various issues with using Object.is

### ISSUE THREAD

**Issue by infinity0** [WebReflection/es6-collections#23]
Unfortunately, Object.is doesn't exist on PhantomJS nor IE or Safari, leading to runtime errors:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Browser_compatibility

It's also not correct according to the semantics of ES6 collections:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Key_equality
vs
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Description

It would be better to define a function like:

~~~~
is = function(a,b) { return isNaN(a)? isNaN(b): a === b; }
~~~~

**Comment by infinity0** [comment]
commit infinity0/es6-collections@8330e56 fixes this, feel free to pull

**Comment by WebReflection** [comment]
I don't think it's wise to polyfill Object.is here, this has nothing to do with Object.is.

**Comment by infinity0** [comment]
Please re-read the commit, this is not about polyfilling Object.is. es6-collections uses a local variable function "is", which is what I'm redefining so it fits the standards.

**Comment by WebReflection** [comment]
not sure I see the +0 VS -0 fixed in any of these commits, what am I missing?

**Comment by infinity0** [comment]
`+0` vs `-0` is handled by `===` - also note the test I changed, which explicitly checks if both `+0` and `-0` are in the map after only adding `-0`.

**Comment by WebReflection** [comment]
nope, `-0 === 0` is true here

**Comment by infinity0** [comment]
Yes, that is the correct behaviour according to the updated standards. Using `Object.is(+0, -0)` will give you `false`, which is incorrect.

**Comment by WebReflection** [comment]
are you reading?

**Comment by WebReflection** [comment]
or maybe I am not. Should -0 and +0 be threaded as same value? if not, this patch needs an update since it was using Object.is before and now it will return a different thing for +0 and -0

If that's how it should be, it's a breaking change so needs a bumped major version too.
