### ISSUE TITLE
es6-collections implementation should be used in Safari 7.1/8

### ISSUE THREAD

**Issue by bmesuere** [WebReflection/es6-collections#27]
Safari 7.1 and 8 have native support for Set and Map, so es6-collections isn't used in those browsers. The Safari implementation, however, is seriously crippled because the Iterator returned by the `keys`, `values` and `entries` functions does not support `next()`. Because these are common functions, the native implementation can not be used reliably:

```JavaScript
m = new Map();
m.set(1, "test");
m.set("2", false);
it = m.values(); // returns Map Iterator
it.next(); // TypeError: undefined is not a function
```

In this case, the es6-collections implementation should be used over the native one, or at least the option to force it should be present.

**Comment by adius** [comment]
+1

**Comment by Steditor** [comment]
https://github.com/Steditor/es6-collections-iterators can be used to patch the `key`, `values` and `entries` functions.
We still have to discuss, whether forcing the whole es6-collections polyfill or patching solely the broken methods is better - I'd like to stick to the native implementation where possible, but that might maybe introduce more problems in some cases.

**Comment by WebReflection** [comment]
actually a good point, using native is always usually better/faster/etc.etc ... but in case of WeakMap there's no way this poly would bring any benefit compared to the native one.

How would you like a partial fix for Safari that  won't fix WeakMap anyway? It seems like maybe Safari needs indeed a fix for its own  broken thing only, I will think about a solution here too.

**Comment by WebReflection** [comment]
scratch that,  WM doesn't need iterators ^_^

**Comment by adius** [comment]
@WebReflection The latest version of https://github.com/Steditor/es6-collections-iterators also fixes Safari!

**Comment by WebReflection** [comment]
current `0.5.2` version of this one fixes Safari too
