### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by robianmcd** [WebReflection/es6-collections#28]
Hi,

Just wondering what versions of Internet Explorer this library supports.

Thanks

**Comment by WebReflection** [comment]
I actually don't know myself ... and I've tried to shut down this project already few times so ... what I can say is that IE9 is OK with [Symbol polyfill](https://github.com/WebReflection/get-own-property-symbols) that would be a way more compliant way to introduce WeakMap anywhere out there ... 

so, are you targeting iE8 ? that's tough. Anything more modern? That's OK, you have options!

**Comment by robianmcd** [comment]
ok thanks for the info. I just need it to run in IE9 so I should be good
