### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by adius** [WebReflection/es6-collections#31]
Releases should not only be pushed to npm but also be tagged accordingly.

**Comment by WebReflection** [comment]
I do that with every other project I maintain ... here I've never tagged a single push. I guess too late now?

**Comment by adius** [comment]
No, not at all:
https://git-scm.com/book/en/v2/Git-Basics-Tagging#Tagging-Later

**Comment by WebReflection** [comment]
right, I've tagged before and after Safari through `0.5.2` and `0.5.1`

thanks for the hint, didn't actually know you could amend tags actually adding them
