### ISSUE TITLE
Map.clear() bug.

### ISSUE THREAD

**Issue by keypointer** [WebReflection/es6-collections#35]
_keys variable is not initialized after running clear method .

```javascript
var m = new Map();
m.set("a", 1);
m.set("b", 2);
m.clear();
//{_itp: Array[0], _keys: Array[2], _values: Array[0], objectOnly: undefined, size: 0}
```

**Comment by WebReflection** [comment]
AFAIK clear has been removed from standard ... was thhat for `WeakMap` only?

**Comment by keypointer** [comment]
Only to the case of "Map.clear ()". In the case of Map and Set "clear ()" method is defined . However, in the case of WeakMap and WeakSet is "clear ()" method was not used because it is not defined by the standard .

**Comment by WebReflection** [comment]
I see, will have a look as soon as I can.

**Comment by bmesuere** [comment]
The `_keys` array should indeed also be cleared: http://www.ecma-international.org/ecma-262/6.0/#sec-map.prototype.clear

**Comment by WebReflection** [comment]
if that's it (apologies I didn't notice that) it should be fixed on 0.5.4

please let me know if that's the case

**Comment by bmesuere** [comment]
Clearing `_keys` does indeed fix this issue. I'm not sure what should happen to the iterator pointer array.

**Comment by WebReflection** [comment]
no idea, but if you clear while iterating, I think you have two problems :D
