### ISSUE TITLE
The fix for IE11 issue not included in es6-collections.js

### ISSUE THREAD

**Issue by Goldenyz** [WebReflection/es6-collections#37]
mdvorscak has reports the IE11 issue. And I can see the fix in index.js. But the code change is not included in the minified file. Might be a build issue?
![image](https://cloud.githubusercontent.com/assets/8434711/9326276/34b00c62-45cb-11e5-943b-0579d9c53ccf.png)

**Comment by MadLittleMods** [comment]
:+1: WebReflection/es6-collections#33 was closed by a PR that fixed the issue but the standalone build `es6-collections.js` does not have this change.

**Comment by WebReflection** [comment]
pushed right now. Please let me know  if there's something  else. thanks

**Comment by Goldenyz** [comment]
When will it be released?

**Comment by WebReflection** [comment]
I've pushed 0.5.5, placed the tag, and published to npm just now

**Comment by Goldenyz** [comment]
Great, thx!
