### ISSUE TITLE
Make it available via bower

### ISSUE THREAD

**Issue by tomecko** [WebReflection/es6-collections#38]

**Comment by WebReflection** [comment]
PR welcome

**Comment by tomecko** [comment]
https://github.com/WebReflection/es6-collections/pull/39
then run `bower register ...` (see http://bower.io/docs/creating-packages/)

**Comment by WebReflection** [comment]
![little-youdontsay](https://cloud.githubusercontent.com/assets/85749/9970414/efd7ca4a-5e4c-11e5-850d-54e421d233c7.png)

**Comment by tomecko** [comment]
Good to know you know what to do...

**Comment by stryju** [comment]
@tomecko two options:
1. stop using bower (npm ftw)
2. write a nice PR w/ bower file

appreciate author's work

**Comment by tomecko** [comment]
Why did you close the issue? Have you seen https://github.com/WebReflection/es6-collections/pull/39?

**Comment by tomecko** [comment]
Great, thanks for merging and for the work on this repo ;)
