### ISSUE TITLE
Not working in IE11/10/9 with aurelia

### ISSUE THREAD

**Issue by SorenMuller** [WebReflection/es6-collections#40]
Hi,

I'm not sure if this is the right place, but here goes..

I'm running Aurelia beta 1 and have added

github:webreflection/es6-collections@master and github:polymer/mutationobservers.
also added script references in index.html..

But when I run i IE, I get several errors ..

Out of stack space
Evaluating http://localhost/Webfragt2.Webclient/jspm_packages/npm/core-js@1.2.6/modules/es6.map.js

Potentially unhandled rejection [2] Error: Expected object
Error loading http://localhost/Webfragt2.Webclient/jspm_packages/npm/core-js@1.2.6/modules/es6.map.js
Unhandled promise rejection Error: Out of stack space
Error loading http://localhost/Webfragt2.Webclient/jspm_packages/npm/aurelia-loader-default@1.0.0-beta

**Comment by zloirock** [comment]
@SorenMuller why do you need `es6-collections` with `aurelia` if `core-js` which `aurelia` uses already contains collections polyfills? `core-js` detects / fixes problems only in the native environment, not in other polyfills.

**Comment by WebReflection** [comment]
yep, beside DOM related polyfills I think you shouldn't mess up with the core. IIRC `core.js` also does a better job than  this library in terms of weakness so if you have core.js in stick with it.
