### ISSUE TITLE
use of non standard properties in the test unit, versus `Array.from()`

### ISSUE THREAD

**Issue by obiot** [WebReflection/es6-collections#43]
from an es6 point of view, the following line is not correct as `_values` is a private property
https://github.com/WebReflection/es6-collections/blob/master/test/index.js#L284

So instead of doing
````javascript
assert(JSON.stringify(o._values) === JSON.stringify([1, 3, 0]));
````

it should rather use [`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) (es6, so requires a polyfill on some browser), that allows to create a new Array instance from an array-like or iterable object. :
````javascript
assert(JSON.stringify(Array.from(o.values())) === JSON.stringify([1, 3, 0]));
````

but then, the problem then is that `Array.from` does not work with the "fake" operator returned by `o.values()`.

any chance you could look at it ?

**Comment by WebReflection** [comment]
iterables requires Symbols, this polyfill has no Symbols polyfill ... right?

The test is just quickly checking results are expected. I know it's quick and dirty, but I think it worked for the last 4 years so this ain't gonna change (I really don't have much time or interest for this project, feel free to use any other better alternative)

**Comment by obiot** [comment]
no worries, thanks for the feedback !

However if I may, othen than closing these tickets, you could also/rather indicate on the "main page" that you do not maintain this anymore ?

**Comment by obiot** [comment]
and thanks for the great work you provided all these years too :)

**Comment by obiot** [comment]
my bad, it is indicated ? or just added it ? :)

**Comment by WebReflection** [comment]
me being lazy, eventually I've managed to update both [README](https://github.com/WebReflection/es6-collections#deprecated) and deprecate this module on `npm`.

It was really a quick fix that lasted even too much ;-)

Sorry for any inconvenience

**Comment by WebReflection** [comment]
also, I've closed these because I wanted to flag them as won't fix but apparently labels on github don't work anymore `¯\_(ツ)_/¯`
