### ISSUE TITLE
Key equality

### ISSUE THREAD

**Issue by obiot** [WebReflection/es6-collections#44]
other point we identified that is different from the latest es6 spec, is that `Map#set` expects `0` and `-0` keys to be unique, which was only valid in an earlier version of the standard

@see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Key_equality

````
In earlier versions of the ECMAScript 6 draft -0 and +0 were considered distinct (even though -0 === +0), this has been changed in later versions and has been adapted in Gecko 29 (Firefox 29 / Thunderbird 29 / SeaMonkey 2.26) (bug 952870) and a recent nightly Chrome.
````

**Comment by WebReflection** [comment]
0 and -0 requires a proper `Object.is` polyfill, which isn't in here.

Again, apologies but I don't really care much about this project. Feel free to send a PR or simply use better alternatives if it's fully standard compliant polyfills that you are looking for:
https://github.com/paulmillr/es6-shim

Best Regards
